### ISSUE TITLE
[1주차] 테스트 코드 주기 정리 및 후기

### ISSUE THREAD

**Issue by ch200203** [HLI-BackEnd-Study/TDD-Study#1]
### 테스트 주도 개발

테스트 주도개발의 주기

1. 작은 테스트를 하나 추가한다.
2. 모든 테스트를 실행해서 테스트가 실패하는 것을 확인한다.
3. 조금 수정한다.
4. 모든 테스트를 실행해서 테스트가 성공하는 것을 확인한다.
5. 중복을 제거하기 위해 리팩토링을 한다
    1. 프로그램에서는 중복을 제거해주면 의존성도 같이 제거된다.
    2. 오직 한 가지의 코드 수정을 통해 다음 테스트도 통과되게 만들 가능성을 최대화 한다.

```java
// Dollar.class
int amount;

public Dollar(int amount) {
	this.amount = amount;
}

public void times() {
	amount = 5 * 2; // <= 코드의 중복을 발생시키는 구문이 됨.
}
//중략

// MoneyTest.class

@Test
public void testMultiplication() {
  Dollar five = new Dollar(5);
  five.times()
  assertEquals(10, product.getAmount());
}
```

---

**TDD의 핵심은 작은 단계를 밟아 나가야 한다.

일반적인 TDD의 주기

1. 테스트를 작성한다.
2. 실행 가능하게 만든다.
    1. 제일 중요한것은 Green Light 를 보는 것!
    2. 실행가능하게 하기 위해서 어떤 방법을 써도 좋다.
3. 올바르게 리팩토링 한다.

테스트 주도 개발을 통해 느낄 수 있는 것

- **각각의 테스트가 기능의 작은 변경에도 얼마나 커버가 되는지**
- **새 테스트를 동작하기 위해 얼마나 많은 하드 코딩을 하는지**
- **테스트를 얼마나 자주 실행하는지**
- **수없이 작은 단계를 거치면서 수많은 리팩토링을 합니다.**

---

느낀점

올바르게 리팩토링 한다는 것 → 이부분이 테스트 코드의 핵심이라고 생각합니다.

특히 이 리팩토링의 범위 내에는 테스트 코드 자체의 리팩토링도 포함된다고 생각해요.
하지만, 이렇게 되면 관리해야할 코드의 양이 점점 늘어나게 되어 관리할 포인트가 많아 질 수도 있다고 생각합니다. 예를 들면 자바에서 코틀린으로 마이그레이션하는 과정에서 테스트 코드도 함께 변경해야 하기 때문에 더 많은 노력과 시간이 들어가겠죠…? 테스트 코드를 작성할 때 그럼 얼마만큼의 테스트 코드의 양을 유지하는게 적절할까요? 혹은 어떤 기준을 두고 테스트 코드를 작성하는게 좋을까요?

**Comment by herbtea30** [comment]
제 생각에는 테스트 코드의 양은 비즈니스 로직을 분석한 이후에, 설계에 따라서 달라지기 때문에 양을 수치로 정하는건 어려울 것 같아요. 
테스트의 기준은 비즈니스 요구사항에 대한 해피케이스와 엣지 케이스를 고려해서 작성한다 정도로 할 것 같아요.
