### ISSUE TITLE
[3주차] BANK...

### ISSUE THREAD

**Issue by hjlee01** [HLI-BackEnd-Study/TDD-Study#10]
## 정리

다형성 : 부모 클래스 타입의 참조 변수로 자식 클래스 타입의 인스턴스를 참조할 수 있도록 하여 구현

- Expression : 산술 연산자들의 집합?
- Sum : 통화 더하기
- Bank : 환전 (reduce : 환율계산)
- Pair : 환율 해시 테이블을 사용하기 위한 두 통화의 쌍

> Expression

`Money reduce(Bank bank, String to);`

> Bank

```
Money reduce(Expression source, String to) {
   return source.reduce(this, to);
}

int rate(String from, String to) {
   if (from.equals(to)) return 1;
   Integer rate = (Integer) rates.get(new Pair(from, to));
   return rate.intValue();
}

void addRate(String from , String to, int rate) {...}
```

> Sum

```
public Money reduce(Bank bank, String to) {
   int amount = augend.amount + addend.amount;
   return new Money(amount, to);
}
```

> Money

```
public Money reduce(Bank bank, String to) {
   int rate = bank.rate(currency, to);
   return new Money(amount / rate, to);
}
```

컴포지트 패턴 : 객체들의 관계를 트리 구조로 구성하여 부분-전체 계층을 표현하는 패턴

픽스처 : 여러 테스트에 걸쳐 객체들을 세팅하는 코드가 동일한 경우 

## 느낀 점

1.  테스트 코드를 통해 구상 클래스에서 추상 클래스화하는 과정
2. 동일한 테스트가 다양한 경우를 다루게 한다 
3. 변수명의 중요성

**Comment by herbtea30** [comment]
변수명과 클래스명의 중요성 동의 합니다.

**Comment by ch200203** [comment]
변수명 함수명 클래명 짓기
패키지를 어떻게 구성할 것인지 
클래스의 책임을 어디까지 볼것인지

비즈니스도 어렵지만 이런 문제들은 마주할 때 마다 많은 고민이 드는것 같습니다....

**Comment by mjkim103301** [comment]
Sum 부분에 작성하신 코드가 메서드명은 환전인데 안의 내용은 덧셈같아보입니당~
``java
public Money reduce(Bank bank, String to) {
   int amount = augend.amount + addend.amount;
   return new Money(amount, to);
}
```

**Comment by mjkim103301** [comment]
느낀점 2번 내용은 `테스트 커버리지를 높이기 위해 테스트코드를 늘리지 말고 구현코드를 줄여서 동일한 테스트가 다양한 경우를 다르게 해야한다`는 것 같아요.
저도 100% 의미를 이해하지는 못했어요 😭
