### ISSUE TITLE
[5주차] xUnit -> JUnit

### ISSUE THREAD

**Issue by ch200203** [HLI-BackEnd-Study/TDD-Study#17]
### 19장 **테이블 차리기**

테스트를 하다보면 발생하는 3가지 패턴 (Bill Wake의 3A)

1. Arrange - 객체를 생성
2. Act - 어떤 자극
3. Assert - 결과를 검사

1. 성능:
    - 여러 테스트가 같은 객체를 사용하면, 효율적이다.
    - 테스트에 사용되는 객체를 재활용
    - Fixture?
        - **여러 테스트에서 같은 Data 를 사용해야 할 때, 코드의 중복을 없애주는 역할을 하는 테스트 전용 데이터이다.**
            - 예를 들어, CarTest 와 CarsTest 둘 다 동일하게 사용하는 데이터가 있다면
            - 그 객체를 Test Fixture 로 생성을 해두고, 그 객체를 두 곳에서 가져다 쓰는 형식이다.
            - [[참고링크](https://tjdtls690.github.io/studycontents/java/2022-10-10-test_fixture/)](https://tjdtls690.github.io/studycontents/java/2022-10-10-test_fixture/)
2. 격리:
    - 한 테스트가 다른 테스트의 결과에 영향을 미치지 않아야한다.
    - Mock, Stub 둘의 차이는?
        - **Stub**:
            - Stub은 테스트에서 의존성을 대체하는 간단한 객체입니다.
            - 주로 미리 정해진 결과를 반환하도록 설정됩니다.
            - 특정 조건에서 특정 값을 반환하거나, 특정 행동을 수행하지 않는 것으로 설정
            - 예시: 데이터베이스에서 데이터를 읽어오는 부분을 Stubbing하여 테스트 중 실제 데이터베이스에 접근하지 않고, 미리 정의된 데이터를 반환하도록 설정할 수 있습니다.
        - **Mock**:
            - Mock은 테스트 중에 의존성의 동작을 검증하기 위한 객체
            - Mock 객체는 기대하는 동작이 실제로 발생했는지 확인할 수 있도록 설정할 수 있습니다.
            - 특정 메서드가 호출되었는지, 호출된 횟수는 몇 번인지, 어떤 인자로 호출되었는지를 검증할 수 있습니다.
            - 예시: 서비스 클래스에서 데이터베이스 저장 메서드가 정확히 한 번 호출되었는지 확인하는 테스트를 할 때 Mock을 사용할 수 있습니다.
        
        ```java
        public class MyTest {
        
            @Mock
            private MyDependency myDependency;
        
            private MyService myService;
        
            @BeforeEach
            public void setUp() {
                MockitoAnnotations.initMocks(this);
                myService = new MyService(myDependency);
            }
        
            @Test
            public void testWithStub() {
                // Stub 설정: myDependency.someMethod()가 호출되면 "stubbed result" 반환
                when(myDependency.someMethod()).thenReturn("stubbed result");
        
                // 테스트 코드
                String result = myService.callDependency();
                assertEquals("stubbed result", result);
            }
        
            @Test
            public void testWithMock() {
                // Mock 설정: myDependency.someMethod()가 호출되었는지 검증
                myService.callDependency();
        
                // Mock 검증: someMethod()가 한 번 호출되었는지 확인
                verify(myDependency, times(1)).someMethod();
            }
        }
        
        ```
        

### xUnit 패턴이란?

xUnit 패턴은 여러 언어에서 유닛 테스트 프레임워크의 구조와 동작을 표준화하는 패턴

- **TestCase**: 각 테스트를 정의하는 기본 단위
- **TestSuite**: 여러 테스트 케이스를 그룹화하여 한 번에 실행
- **TestResult**: 테스트 실행 결과를 기록하고 요약
- **TestRunner**: 테스트를 실행하고 결과를 출력

### 1. TestCase 클래스

`TestCase` 클래스는 모든 테스트 케이스의 기본 구조를 정의합니다. 각 테스트 메서드는 `run` 메서드에서 실행됩니다. 이 클래스는 테스트의 전처리(`setUp`)와 후처리(`tearDown`)를 정의할 수 있도록 합니다.

```kotlin
abstract class TestCase(val name: String) {

    open fun setUp() {}

    open fun tearDown() {}

    fun run(result: TestResult) {
        result.testStarted()
        setUp()
        try {
            val method = this::class.members.find { it.name == name } as KFunction<*>
            method.call(this)
        } catch (e: Exception) {
            result.testFailed()
        }
        tearDown()
    }
}

```

### 2. WasRun 클래스

`WasRun` 클래스는 `TestCase`를 상속하며, 실제 테스트 메서드와 그 로그를 관리합니다. 예제에서는 `testMethod`와 `testBrokenMethod`를 정의합니다.

```kotlin
class WasRun(name: String) : TestCase(name) {
    var wasRun: Int? = null
    var log: String = ""

    override fun setUp() {
        wasRun = null
        log = "setUp "
    }

    override fun tearDown() {
        log += "tearDown "
    }

    fun testMethod() {
        wasRun = 1
        log += "testMethod "
    }

    fun testBrokenMethod() {
        throw Exception()
    }
}

```

### 3. TestResult 클래스

`TestResult` 클래스는 테스트 실행 결과를 기록합니다. 각 테스트가 시작될 때와 실패할 때 카운트를 증가시킵니다.

```kotlin
class TestResult {
    var runCount = 0
    var failureCount = 0

    fun testStarted() {
        runCount++
    }

    fun testFailed() {
        failureCount++
    }

    fun summary(): String {
        return "$runCount run, $failureCount failed"
    }
}

```

### 4. TestSuite 클래스

`TestSuite` 클래스는 여러 테스트를 그룹화하여 한 번에 실행할 수 있게 합니다.

```kotlin
class TestSuite {
    private val tests = mutableListOf<TestCase>()

    fun add(test: TestCase) {
        tests.add(test)
    }

    fun run(result: TestResult) {
        tests.forEach { it.run(result) }
    }
}

```

### 5. TestCaseTest 클래스

`TestCaseTest` 클래스는 실제로 테스트를 정의하고 실행하는 곳입니다. 여기서는 여러 테스트 메서드를 정의하여 각각의 기능을 검증합니다.

```kotlin
class TestCaseTest(name: String) : TestCase(name) {

    private lateinit var result: TestResult

    override fun setUp() {
        result = TestResult()
    }

    @Test
    fun testTemplateMethod() {
        val test = WasRun("testMethod")
        test.run(result)
        assertThat(test.log).isEqualTo("setUp testMethod tearDown ")
    }

    @Test
    fun testResult() {
        val test = WasRun("testMethod")
        test.run(result)
        assertThat(result.summary()).isEqualTo("1 run, 0 failed")
    }

    @Test
    fun testFailedResult() {
        val test = WasRun("testBrokenMethod")
        test.run(result)
        assertThat(result.summary()).isEqualTo("1 run, 1 failed")
    }

    @Test
    fun testFailedResultFormatting() {
        result.testStarted()
        result.testFailed()
        assertThat(result.summary()).isEqualTo("1 run, 1 failed")
    }

    @Test
    fun testSuite() {
        val suite = TestSuite()
        suite.add(WasRun("testMethod"))
        suite.add(WasRun("testBrokenMethod"))
        suite.run(result)
        assertThat(result.summary()).isEqualTo("2 run, 1 failed")
    }
}

```

⇒ 전체적으로 돌아보면… JUnit 을 사용하면 될 듯합니다..!

**Comment by mjkim103301** [comment]
코틀린으로 바꿔서 정리해주셨네요!👍
