### ISSUE TITLE
[2주차] 팩토리 메서드

### ISSUE THREAD

**Issue by mjkim103301** [HLI-BackEnd-Study/TDD-Study#5]
## 새로 알게된 점
팩토리 메서드를 통해 자식 클래스의 기능을 부모 클래스에 공통화한 후, 자식 클래스를 제거할 수 있다.

1. 상속 구조로 부모 클래스: Money, 자식 클래스: Dollar, Franc을 만든다.
2. Dollar, Franc의 공통 변수 메서드를 Money에 만들고, 자식 클래스의 중복 코드를 제거한다.
3. 자식 클래스에 파라미터, 메서드가 없다면 자식 클래스를 제거한다. 

```java
public class Money {
 protected int amount;
 protected String currency;

 Money(int amount, String currency) {
  this.amount = amount;
  this.currency = currency;
 }

 static Money franc(int amount) {
  return new Money(amount, "CHF"); 
 }

 static Money dollar(int amount) {
  return new Money(amount, "USD");
 }

 Money times(int multiplier) {
  return new Money(amount * multiplier, currency);
 }

 public boolean equals(Object object) {
  Money money = (Money) object;
  return amount == money.amount && currency().equals(money.currency());
 }

}
```  
## 궁금한 점
자식 클래스를 제거하는 것이 좋은 것일까요?

**Comment by herbtea30** [comment]
자식 클래스에 생성자 밖에 없다면, 제거할 꺼 같아요. 단, 인터페이스로 설계한 경우라면 다르겠지만요.
인터페이스로 설계를 해서, 구현체의 여러 클래스의 메소드가 동일한 동작을 한다면??
생각해볼만한 문제인거 같아요
