### ISSUE TITLE
[2주차] 테스트 코드는 설계품질 개선에 도움이 된다!

### ISSUE THREAD

**Issue by ch200203** [HLI-BackEnd-Study/TDD-Study#7]
### 삼각측량 방법 사용에 대한 생각

삼각측량이란 `어떤 한 라디오 송신국에서 두 개의 수신국으로 라디오를 쏘면 송신국의 정확한 위치를 알 수 있는 방법`

이를 코드에 적용시킨다면

```java
@Test
public void testEquality() {
    assertTrue(new Dollar(5).equals(new Dollar(5)));   // 1번 수신국
    assertFalse(new Dollar(5).equals(new Dollar(10))); // 2번 수신국
}
```

`testEquality()`  메서드를 반드시 성공하게 하기 위하여 `equlas()` 가 반드시 `true`  를 반환하게 하였기 때문에 실제 로직이 동작할 수 있게하는 코드를 만드는것.

→ 중복되는 코드가 항상 발생할 수 밖에 없다.
항상 이 방법을 따르는 것은 비효율적이다. 꼭 필요한 경우가 아니라면 지양하자.(리팩토링을 어떻게 수행해야 할지 모르겠을 때 사용하면 좋다고 합니다.)

### 충분한 테스트가 필요한 이유

충분한 테스트가 없다면 테스트가 없는 채로 리팩토링이 이루어짐 → 리팩토링 과정에서의 실수가 발생할 가능성이 높고 실수가 발생된 채로 테스트가 통과되게 됨.

따라서 있어야 할 것 같은 테스트를 작성해야한다!

→ 필요한 테스트종류에는 무엇이 있을까요?

- 지난 회차의 몇개의 테스트가 필요할까와 같은 맥락으로 생각해 보았을 때
- 해피 케이스도 중요하지만 엣지 케이스, 그리고 예외가 발생될법한 상황들을 생각해보자.
    - 엣지나 예외가 발생될 상황들 즉 비즈니스에 맞춰서 테스트
    - 코드적으로 안전한지에 대한 테스트? (예를 들어 불변과 같은)는 필요하지 않을까?

### 객체 만들기

상속을 통해서 타입계층을 구현하고 테스트 코드에서 콘트리트 하위 클래스 존재 사실을 분리한다.

**이야기 해볼 거리**

테스트를 통해 코드 설계를 개선해나감.

> ***Well Grounded Java Developer***
테스트 주도 개발의 기본 전제는 테스트를 구현하기 전에 작성하자는 것입니다. 이를 통해 테스트가 코드 설계에 영향을 미칩니다.테스트가 설계와 구현을 주도할 것입니다.
> 

> ***구글 엔지니어는 이렇게 일한다***
테스트를 작성하는 행위는 시스템의 설계도 개선해줍니다. 테스트는 시스템 코드의 첫번째 고객이라는 자격으로 여러분이 설계한 설계에 관해 많은 이야기를 해줍니다. 데이터베이스에 너무 강하게 묶여 있는지. 이 API가 필수 유스케이스를 지원하는지, 시스템이 극단적인 상황들에 잘 대처하는지 등을 확인할 수 있습니다.
> 

> *Franc 생성자에서 currency를 받도록 수정하였더니 Money의 franc 팩토리 메소드와 times 메소드 두 곳이 깨짐*
일단 하던 구현을 마친 후에  고치는 것이 맞을까…? 라는 생각이 들었음.
*→* 테스트 코드를 작성하다가 중간에 더 좋은 방향이 있다면 전체적으로 리팩토링 하는 것이 맞을까
> 

 혼자서 구현 할 때는 괜찮겠지만 다같이 하는 프로젝트 에서는…?

**Comment by mjkim103301** [comment]
테스트 코드를 작성하다가 다른 부분에서 에러가 발생했을 때, 제가 짠 코드만 해당되거나 수정 범위가 작은 경우 전체적으로 리펙토링하는 편입니다.
만약 수정 범위가 큰 경우는 수정 전 공유를 먼저 하는 편인 것 같아요~

**Comment by herbtea30** [comment]
TDD의 형태로 개발을 진행해보지 않아서 낯설지만
저라면, 테스트코드에서 생성자를 수정하는 테스트를 짜면서, 프로덕션 코드에 반영하고, 그에 수반되는 에러들도 같이 잡을 꺼 같아요.
