### ISSUE TITLE
[2주차] 우리가 사는 곱하기

### ISSUE THREAD

**Issue by hjlee01** [HLI-BackEnd-Study/TDD-Study#8]
## 정리

> 6장. 상속과 리팩토링

Money 클래스 생성

> 7장. You can’t compare dollar and franc

Dollar 와 Franc 을 비교하기 위한 equals 문 수정

> 8장. 팩토리 메서드 패턴

하위 클래스에서 팩토리 메서드를 오버라이딩해서 객체를 반환하게 하는 패턴

> 9장. 우리가 사는 곱하기

> 10장. 콘크리트 클래스 ( 구상 클래스 )

new 연산자를 사용하여 인스턴스를 생성할 수 있는 클래스

## 느낀 점
짐 코플린 규칙 : 하던 일을 중단하고 다른 일을 하는 상태에서 그 일을 또 중단하지는 않는다.
TDD 와 [디자인 패턴](https://namu.wiki/w/%EB%94%94%EC%9E%90%EC%9D%B8%20%ED%8C%A8%ED%84%B4)

**Comment by mjkim103301** [comment]
이슈 제목이 "우리가 사는 곱하기"인 이유가 궁금하네요! 스터디 시간이 기다려지네요 ㅎㅎ

**Comment by herbtea30** [comment]
9장이 의미 깊으셨나요? 제목이..?
